# Generated by Django 4.1.4 on 2022-12-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jhonn', '0002_alter_skills_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
