# Generated by Django 4.1.4 on 2022-12-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jhonn', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='career',
            field=models.CharField(max_length=50),
        ),
    ]
