# Generated by Django 4.1.4 on 2022-12-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jhonn', '0004_alter_about_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='greetings_2',
            field=models.CharField(max_length=6),
        ),
    ]
